// 게시판 타입에 전체 게시물
GET http://{{host}}/board/1/article
Accept: application/json

> {%
client.test("get all articles by boardId", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

%}

###

// 게시물 1건 상세
GET http://{{host}}/board/1/article/2
Accept: application/json

> {%
client.test("get article by articleId", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

// 게시물 등록
POST http://{{host}}/board/2/article
Content-Type: application/json

< ./data/article.json

> {%
client.test("post article", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###


