INSERT INTO BOARD_MASTER (BOARD_TYPE,
                          BOARD_NAME,
                          BOARD_DESCRIPTION,
                          ATTACH_FILE_LIMIT,
                          REPLY_YN,
                          COMMENT_YN,
                          USE_YN,
                          REGISTER_ID)
VALUES ('PORTAL',
        '통합게시판1',
        '통합게시판입니다.',
        0,
        'Y',
        'Y',
        'Y',
        'ADMIN'),
       ('PORTAL',
        '통합게시판2',
        '통합게시판입니다.',
        0,
        'N',
        'Y',
        'Y',
        'ADMIN'),
       ('PORTAL',
        '통합게시판3',
        '통합게시판입니다.',
        0,
        'Y',
        'N',
        'Y',
        'ADMIN'),
       ('PORTAL',
        '통합게시판4',
        '통합게시판입니다.',
        0,
        'N',
        'N',
        'Y',
        'ADMIN'),
       ('PORTAL',
        '통합게시판5',
        '통합게시판입니다.',
        0,
        'N',
        'N',
        'N',
        'ADMIN')
;


INSERT INTO BOARD_ARTICLE (PARENT_ARTICLE_ID,
                           BOARD_ID,
                           NOTICE_YN,
                           TITLE,
                           CONTENTS,
                           READ_COUNT,
                           USE_YN,
                           REGISTER_ID)
VALUES (NULL,
        1,
        'N',
        '테스트게시물1',
        '테스트게시물1 내용',
        5,
        'Y',
        'TESTER'),
       (NULL,
        1,
        'N',
        '테스트게시물2',
        '테스트게시물2 내용',
        0,
        'Y',
        'TESTER'),
       (NULL,
        1,
        'N',
        '테스트게시물3',
        '테스트게시물3 내용',
        2,
        'Y',
        'TESTER'),
       (NULL,
        2,
        'N',
        '테스트게시물4',
        '테스트게시물4 내용',
        5,
        'Y',
        'TESTER'),
       (NULL,
        3,
        'N',
        '테스트게시물5',
        '테스트게시물5 내용',
        9,
        'N',
        'TESTER')
;
