DROP TABLE IF EXISTS BOARD_COMMENT;
DROP TABLE IF EXISTS BOARD_ARTICLE;
DROP TABLE IF EXISTS BOARD_MASTER;

CREATE TABLE IF NOT EXISTS BOARD_MASTER (
    BOARD_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOARD_TYPE VARCHAR(50) NOT NULL DEFAULT 'PORTAL',
    BOARD_NAME VARCHAR(500) NOT NULL,
    BOARD_DESCRIPTION VARCHAR(1000),
    ATTACH_FILE_LIMIT INT DEFAULT 0,
    REPLY_YN VARCHAR(1) DEFAULT 'N',
    COMMENT_YN VARCHAR(1) DEFAULT 'N',
    USE_YN VARCHAR(1) DEFAULT 'Y',
    REGISTER_ID VARCHAR(50) NOT NULL,
    REGISTER_TIMESTAMP TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_ID VARCHAR(50),
    UPDATE_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BOARD_ARTICLE (
    ARTICLE_ID INT AUTO_INCREMENT  PRIMARY KEY,
    PARENT_ARTICLE_ID INT,
    BOARD_ID INT ,
    NOTICE_YN VARCHAR(1) DEFAULT 'N',
    TITLE VARCHAR(1000),
    CONTENTS VARCHAR(4000),
    READ_COUNT INT DEFAULT 0,
    USE_YN VARCHAR(1) DEFAULT 'Y',
    REGISTER_ID VARCHAR(50) NOT NULL,
    REGISTER_TIMESTAMP TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_ID VARCHAR(50),
    UPDATE_TIMESTAMP TIMESTAMP,
    FOREIGN KEY (BOARD_ID) REFERENCES BOARD_MASTER(BOARD_ID)
);

CREATE TABLE IF NOT EXISTS BOARD_COMMENT (
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    ARTICLE_ID INT,
    COMMENT VARCHAR(4000),
    USE_YN VARCHAR(1) DEFAULT 'Y',
    REGISTER_ID VARCHAR(50) NOT NULL,
    REGISTER_TIMESTAMP TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_ID VARCHAR(50),
    UPDATE_TIMESTAMP TIMESTAMP,
    FOREIGN KEY (ARTICLE_ID) REFERENCES BOARD_ARTICLE(ARTICLE_ID)
);